import { statusComponents } from '../../shared/constants/status.js';

export const defaultHeartbeats = Array.from({ length: 100 })
  .map((_, i) => ({
    time: Date.now() - i * 10000,
    latency: Math.floor(Math.random() * 100),
  }))
  .reverse();

export const defaultIncidents = [
  {
    message: "I've set my server on fire. Going to take 2 hours to fix it.",
    createdAt: Date.now(),
    status: 'Maintenance',
  },
  {
    message: 'Something is broken, but not sure where 🤷🏽',
    timestamp: Date.now(),
    status: 'Incident',
  },
  {
    message: "IT'S ALL GONE!! We're working on fixing it.",
    timestamp: Date.now(),
    status: 'Outage',
  },
];

export const defaultStatusComponents = [
  { id: 'default-1', isMinimized: false, ...statusComponents.header },
  { id: 'default-2', isMinimized: false, ...statusComponents.status },
  { id: 'default-3', isMinimized: false, ...statusComponents.uptime },
  { id: 'default-4', isMinimized: false, ...statusComponents.metrics },
  { id: 'default-5', isMinimized: false, ...statusComponents.history },
];

export const listOfFonts = [
  'Montserrat',
  'Andalé Mono',
  'Archivo',
  'Arial',
  'Arial Black',
  'Arimo',
  'Barlow',
  'Barlow Condensed',
  'Baskerville',
  'Bradley Hand',
  'Brush Script MT',
  'Cabin',
  'Cairo',
  'Comic Sans MS',
  'Courier',
  'DM Sans',
  'Dosis',
  'Exo 2',
  'Figtree',
  'Fira Sans',
  'Georgia',
  'Gill Sans',
  'Heebo',
  'Helvetica',
  'Hind Siliguri',
  'IBM Plex Sans',
  'Impact',
  'Inter',
  'Josefin Sans',
  'Jost',
  'Kanit',
  'Karla',
  'Lato',
  'Libre Franklin',
  'Lucida',
  'Luminari',
  'Manrope',
  'Monaco',
  'Mukta',
  'Mulish',
  'Nanum Gothic',
  'Noto Sans',
  'Noto Sans JP',
  'Noto Sans KR',
  'Noto Sans SC',
  'Noto Sans TC',
  'Nunito',
  'Nunito Sans',
  'Open Sans',
  'Oswald',
  'Outfit',
  'Palatino',
  'Poppins',
  'PT Sans',
  'PT Sans Narrow',
  'Quicksand',
  'Raleway',
  'Roboto',
  'Roboto Condensed',
  'Rubik',
  'Schibsted Grotesk',
  'Space Grotesk',
  'Tahoma',
  'Teko',
  'Times New Roman',
  'Titillium Web',
  'Trebuchet MS',
  'Ubuntu',
  'Verdana',
  'Work Sans',
];
